"""add_store_table

Revision ID: 0eb0e3db6657
Revises: 9bb0e67dcffd
Create Date: 2026-02-10 03:43:34.903204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb0e3db6657'
down_revision: Union[str, Sequence[str], None] = '9bb0e67dcffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=True)
    op.add_column('orders', sa.Column('store_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'store_id')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
