"""add_sort_order_to_products

Revision ID: e82705c4ab35
Revises: 8c2a9381a64a
Create Date: 2026-02-09 02:54:22.232869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82705c4ab35'
down_revision: Union[str, Sequence[str], None] = '8c2a9381a64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sort_order')
    # ### end Alembic commands ###
